create table item (
 id bigint generated by default as identity,
 item_name varchar(10),
 price integer,
 quantity integer,
 primary key (id)
);

--insert into item (id, item_name, price, quantity) values (1, 'spring', 10000, 100);
--insert into item (id, item_name, price, quantity) values (2, 'mybatis', 20000, 100);