spring:
  profiles:
    include: real-oauth
    active: real
  session:
    store-type: jdbc

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  h2:
    console:
      enabled: true